import assert from "node:assert/strict";
import test from "node:test";

import {
  END_MARKER,
  START_MARKER,
  mergeManagedSection,
  parseGeneratedOutput,
} from "./merge-pr-description.mjs";

test("parses a fenced JSON response", () => {
  const result = parseGeneratedOutput(
    '```json\n{"title":"fix: keep metadata","body":"## Summary\\n\\n- Fixed"}\n```',
    "old title",
  );

  assert.deepEqual(result, {
    title: "fix: keep metadata",
    body: "## Summary\n\n- Fixed",
    usedJson: true,
  });
});

test("falls back to Markdown without replacing the current title", () => {
  const result = parseGeneratedOutput("## Summary\n\n- Fixed", "human title");

  assert.deepEqual(result, {
    title: "human title",
    body: "## Summary\n\n- Fixed",
    usedJson: false,
  });
});

test("appends the managed section without changing human content", () => {
  const human = "@agent pr-title\n\nFixes WEE-123\n\nRisk: L2";
  const merged = mergeManagedSection(human, "## Summary\n\n- Fixed logout");

  assert.ok(merged.startsWith(`${human}\n\n${START_MARKER}`));
  assert.ok(merged.includes("Fixes WEE-123"));
  assert.ok(merged.endsWith(END_MARKER));
});

test("replaces only the existing managed section", () => {
  const current = [
    "Human preface",
    "",
    START_MARKER,
    "old generated text",
    END_MARKER,
    "",
    "Human follow-up",
  ].join("\n");
  const merged = mergeManagedSection(current, "new generated text");

  assert.equal(
    merged,
    [
      "Human preface",
      "",
      START_MARKER,
      "new generated text",
      "",
      "---",
      "*PR description generated by [Agent](https://weekendsuperhero.io)*",
      END_MARKER,
      "",
      "Human follow-up",
    ].join("\n"),
  );
});

test("merging identical generated content is idempotent", () => {
  const first = mergeManagedSection("Human content", "Generated content");
  const second = mergeManagedSection(first, "Generated content");

  assert.equal(second, first);
});

test("refuses malformed markers instead of overwriting human content", () => {
  assert.throws(
    () => mergeManagedSection(`Human\n${START_MARKER}\nbroken`, "Generated"),
    /exactly one complete Agent managed section/,
  );
});

test("refuses generated output containing reserved markers", () => {
  assert.throws(
    () => mergeManagedSection("Human", `Generated ${END_MARKER}`),
    /reserved managed markers/,
  );
});
